#!/bin/bash
# Vercel Environment Variables Quick Copy Script

echo "=== VERCEL ENVIRONMENT VARIABLES ==="
echo ""
echo "Copy these to your Vercel Dashboard:"
echo "Project Settings > Environment Variables"
echo ""
echo "Variable Name                 | Value (replace with actual)"
echo "============================  | ========================="
echo "NODE_ENV                      | production"
echo "DATABASE_URL                  | postgresql://username:password@hostname:port/database?sslmode=require"
echo "SHOPIFY_API_KEY              | your_shopify_api_key_here"
echo "SHOPIFY_API_SECRET           | your_shopify_api_secret_here"
echo "SHOPIFY_SCOPES               | read_products,write_orders,read_customers"
echo "APP_URL                      | https://your-app-name.vercel.app"
echo "MAPBOX_ACCESS_TOKEN          | your_mapbox_token_here (optional)"
echo ""
echo "=== TESTING VARIABLES (Optional) ==="
echo "SHOPIFY_STORE_NAME           | vgpcreatives"
echo "SHOPIFY_STOREFRONT_ACCESS_TOKEN | 172c37b6b7a7759406ad719a4f149d42"
echo "SHOPIFY_PRODUCT_VARIANT_ID   | gid://shopify/ProductVariant/41068385009711"
echo ""
echo "📋 Make sure to set Environment to 'Production' for each variable!"
echo ""